// Scene / word illustrations shown ABOVE questions (kids are visual).
// AI-generated 3D renders (Canva), matched by a keyword in the question text or
// hint — so no backend/API change is needed, it's purely a frontend enhancement.
//
// TWO kinds of art live here:
//
//  1. STATIC requires (`SCENE_RULES`, `PHONICS_WORD_IMAGES`) — the original sets.
//     Only require() images that actually exist in assets, or the bundler fails.
//
//  2. The `assets/objects/` DROP-IN folder — read with require.context, so a new
//     PNG is picked up by its FILENAME with no code change. Name the file after
//     the object (`apple.png`, `sun.png`, `dinosaur.png`) and the rules below
//     will find it. A rule pointing at a file that isn't there yet is harmless:
//     it just falls through, no image, no crash, no build break.
//     Prompts + the full filename list: docs/QUESTION_IMAGE_PROMPTS.md
//
//  3. `/art/<name>.svg` — the built-in glassy 3D illustrations, generated by
//     tools/gen-art.mjs into src/public/art/ and served as static files, so a
//     question is never left bare while the render set is filled in. A PNG of
//     the same name always WINS over the SVG.
//     (They must be files, not inline data URIs: react-native-web 0.21's
//     <Image> silently refuses to render a data:image/svg+xml source.)

import { hasArt } from "./artIndex";


// ── Generated scene art ─────────────────────────────────────────────
// One illustration per scenario. Without these every prompt that had no
// hand-drawn PNG fell through to the subject icon, so two different
// questions showed the same heart. Dual-coding research is clear that a
// picture carrying no information about THIS question adds cognitive load
// rather than removing it, so a repeated icon is worse than none.
//   https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8963493/
const GENERATED_SCENES: [RegExp, string][] = [
  [/wake up on your birthday/i, "scene_birthday"],
  [/open a present|get to open/i, "scene_gift_open"],
  [/big dog barks|dog barks loudly/i, "scene_dog_bark"],
  [/finish a puzzle|puzzle all by yourself/i, "scene_puzzle_done"],
  [/takes your toy|toy without asking/i, "scene_toy_taken"],
  [/cannot find your shoes|find your shoes/i, "scene_lost_shoes"],
  [/grandma gives you a big hug|big hug/i, "scene_hug"],
  [/rains.{0,12}(so )?you cannot go outside/i, "scene_rain_inside"],
  [/picked last|last one picked/i, "scene_last_picked"],
  [/spill juice|spill.*floor/i, "scene_spill"],
  [/nothing to do/i, "scene_bored"],
  [/best friend moves|friend moves to another/i, "scene_friend_moves"],
  [/studied hard but still got/i, "scene_got_it_wrong"],
  [/chosen for something you wanted/i, "scene_jealous"],
  [/told a small lie/i, "scene_guilty"],
  [/read out loud to the whole class/i, "scene_read_aloud"],
  [/helped someone who was struggling/i, "scene_helped"],
  [/did not invite you/i, "scene_not_invited"],
  [/finally learn something/i, "scene_finally_learn"],
  [/whole class of new people/i, "scene_new_class"],
  [/treated unfairly/i, "scene_unfair"],
  [/happy to move to a new school|mixed feelings/i, "scene_mixed"],
  [/BEFORE you speak|take a breath/i, "scene_breathe"],
  [/apologi[sz]es properly|forgive/i, "scene_forgive"],
  [/sneezes near you/i, "scene_sneeze"],
  [/want the bread|pass the bread/i, "scene_pass_bread"],
  [/say to the cook/i, "scene_thank_cook"],
  [/bump into someone/i, "scene_bump"],
  [/present you already own/i, "scene_present_dup"],
  [/(standing in|past someone in) the doorway/i, "scene_doorway"],
  [/visitor arrives/i, "scene_visitor"],
  [/shows you their drawing/i, "scene_friend_drawing"],
  [/need to cough/i, "scene_cough"],
  [/holds a door open/i, "scene_door_held"],
  [/interrupt someone talking/i, "scene_interrupt"],
  [/new child is standing alone/i, "scene_new_child"],
  [/served food you dislike/i, "scene_dislike_food"],
  [/telling a long story|shows you are listening/i, "scene_listening"],
  [/borrowed something and broke/i, "scene_broke_it"],
  [/disagree with a friend/i, "scene_disagree"],
  [/elderly person is standing|offer them your seat/i, "scene_bus_seat"],
  [/win a game against/i, "scene_won_game"],
  [/lose a game/i, "scene_lost_game"],
  [/group chat/i, "scene_group_chat"],
  [/real apology|hurt someone/i, "scene_apology"],
  [/given credit for work/i, "scene_credit"],
  [/running late to meet/i, "scene_late"],
  [/tells you something private/i, "scene_private"],
  [/customs differ/i, "scene_customs"],
];

const SCENE_RULES: [RegExp, any][] = [
  // ── Feelings & Emotions scenarios ──────────────────────────────
  [/surprise gift|got a .*gift/i,          require("../assets/scenes/gift.png")],
  [/best friend moved|moved away/i,        require("../assets/scenes/friend_moved.png")],
  [/takes your toy|toy without asking/i,   require("../assets/scenes/toy_taken.png")],
  [/first chapter book|chapter book/i,     require("../assets/scenes/chapter_book.png")],
  [/loud thunder|thunder/i,                require("../assets/scenes/thunder.png")],
  [/deep breaths|5 deep/i,                 require("../assets/scenes/breathing.png")],
  // ── Manners scenarios ──────────────────────────────────────────
  [/sneezes? near/i,                       require("../assets/scenes/sneeze.png")],
  [/interrupt someone/i,                   require("../assets/scenes/interrupt.png")],
  [/to the cook|finish eating dinner/i,    require("../assets/scenes/thank_cook.png")],
  [/bump into someone/i,                   require("../assets/scenes/bump.png")],
];

// Phonics: object picture for the target word (parsed from the hint, e.g.
// "Rule: short vowel -a- — the word is 'cat'").
const PHONICS_WORD_IMAGES: Record<string, any> = {
  cat:    require("../assets/phonics/cat.png"),
  dog:    require("../assets/phonics/dog.png"),
  pan:    require("../assets/phonics/pan.png"),
  bug:    require("../assets/phonics/bug.png"),
  train:  require("../assets/phonics/train.png"),
  boat:   require("../assets/phonics/boat.png"),
  rain:   require("../assets/phonics/rain.png"),
  green:  require("../assets/phonics/green.png"),
  phone:  require("../assets/phonics/phone.png"),
  knight: require("../assets/phonics/knight.png"),
  hit:    require("../assets/phonics/hit.png"),
  red:    require("../assets/phonics/red.png"),
  play:   require("../assets/phonics/play.png"),
  write:  require("../assets/phonics/write.png"),
  sight:  require("../assets/phonics/sight.png"),
};

// ── Drop-in object registry ───────────────────────────────────────────────────
// Every PNG in assets/objects/ becomes available under its bare filename.
// require.context is a Metro feature (enabled in this Expo/expo-router app); the
// try/catch keeps the app running on any bundler that lacks it.
const OBJECT_IMAGES: Record<string, any> = (() => {
  const out: Record<string, any> = {};
  try {
    // @ts-ignore — require.context is provided by Metro, not by TS
    const ctx = require.context("../assets/objects", false, /\.(png|jpg|jpeg)$/);
    for (const key of ctx.keys()) {
      const name = key.replace(/^\.\//, "").replace(/\.(png|jpg|jpeg)$/i, "").toLowerCase();
      out[name] = ctx(key);
    }
  } catch {
    // No require.context (or no folder yet) — object art simply stays unmatched.
  }
  return out;
})();

// Keyword → object filename (WITHOUT extension). Order matters: first match wins,
// so put the specific scenes above the generic single objects.
const OBJECT_RULES: [RegExp, string][] = [
  // ── Reading comprehension passages ─────────────────────────────
  [/sun rises in the east|light and warmth/i,        "sunrise"],
  [/bears hibernate|hibernate in winter/i,           "bear_hibernating"],
  [/water cycle|evaporation, condensation/i,         "water_cycle"],

  // ── Math word-problem items (QuestionGenerator.ITEMS) ──────────
  [/\bapples?\b/i,                                   "apples"],
  [/\bstickers?\b/i,                                 "stickers"],
  [/\bstamps?\b/i,                                   "stamps"],
  [/\bcrayons?\b/i,                                  "crayons"],
  [/\bcookies?\b/i,                                  "cookies"],
  [/\bmarbles?\b/i,                                  "marbles"],
  [/\bbooks?\b/i,                                    "books"],
  [/\bstars?\b/i,                                    "stars"],

  // ── Geometry ───────────────────────────────────────────────────
  [/of a square/i,                                   "shape_square"],
  [/of a rectangle/i,                                "shape_rectangle"],
  [/of a triangle/i,                                 "shape_triangle"],

  // ── Cultural · Gita values ─────────────────────────────────────
  [/gita value — courage|true courage/i,             "value_courage"],
  [/gita value — steadiness|steadiness means/i,      "value_steadiness"],
  [/gita value — kindness|kindness means/i,          "value_kindness"],
  [/gita value — duty|duty means/i,                  "value_duty"],
  [/gita value — honesty|honesty means/i,            "value_honesty"],
  [/gita value — compassion|compassion means/i,      "value_compassion"],

  // ── Cultural · Tang poems ──────────────────────────────────────
  [/静夜思|moonlight is bright/i,                     "poem_moonlight"],
  [/春晓|spring sleep/i,                              "poem_spring_dawn"],
  [/登鹳雀楼|white sun sets behind/i,                  "poem_stork_tower"],

  // ── Cultural · Spanish vocabulary ──────────────────────────────
  [/'rojo'/i,                                        "color_red"],
  [/'azul'/i,                                        "color_blue"],
  [/'verde'/i,                                       "color_green"],
  [/'casa'/i,                                        "house"],
  [/'agua'/i,                                        "water"],
  [/'sol'/i,                                         "sun"],
  [/'luna'/i,                                        "moon"],
  [/'niño'/i,                                        "boy"],
  [/'niña'/i,                                        "girl"],

  // ── Bare arithmetic — the glyph art, so number-only cards (and the
  //    match-pairs game, which is nothing but number-only cards) still
  //    get a picture. Kept LAST-but-one so any real subject wins first.
  [/add the fractions|\d\/\d\s*\+/i,                 "op_fraction"],
  [/what is \d+\.\d+|\d+\.\d{2}/i,                   "op_decimal"],
  [/what is \d+ ?\+ ?\d+|count up \d+ more/i,        "op_add"],
  [/what is \d+ ?[−-] ?\d+|count back \d+/i,         "op_sub"],
  [/what is \d+ ?[×x*] ?\d+|groups of \d+/i,         "op_mul"],
  [/what is \d+ ?[÷/] ?\d+|how many groups/i,        "op_div"],

  // ── Interest themes (worksheet/passage headers) ────────────────
  [/dinosaur|t-rex|triceratops|fossil/i,             "dinosaurs"],
  [/\bspace\b|planet|rocket|astronaut|comet/i,       "space"],
  [/ocean|whale|coral|seashell|under the sea/i,      "ocean"],
  [/dragon|wizard|castle|magic spell/i,              "fantasy"],
  [/vehicle|\btruck\b|airplane|\bengine\b/i,         "vehicles"],
  [/holiday|birthday|festival|celebration/i,         "holidays"],
  [/\bsports?\b|\bteam\b|\bgoal\b|\bcoach\b/i,       "sports"],
  [/nature|forest|\bflower\b|\bseed\b|\bleaf\b/i,    "nature"],
  [/\banimals?\b|\blion\b|\bowl\b|\belephant\b/i,    "animals"],
];

// ── Tailoring: culture track + age band ──────────────────────────────────────
// A name resolves to the most specific artwork that exists on disk:
//   holidays + zh track          → /art/holidays.zh.svg   (lantern)
//   apples   + TK–1              → /art/apples.tk.svg     (one big apple)
//   anything with no variant     → /art/holidays.svg      (neutral)

export interface ArtContext {
  /** Subject slug — phonics · reading · math · art · story · workbooks · logic · feelings · manners */
  subject?: string;
  /** Interest/topic slug — dinosaurs · space · ocean · animals · … */
  topic?: string;
  /** Grade number (0 = TK) or label, used for the age band */
  grade?: number | string;
  /** Culture track / language: zh · hi · es (en or absent = neutral art) */
  culture?: string;
  /** Free text such as a worksheet title ("Dinosaurs Manners - Grade TK") */
  title?: string;
}

/** TK–1 gets the simpler, chunkier variants; 4–6 the more detailed ones. */
function ageBand(grade?: number | string): string | undefined {
  if (grade === undefined || grade === null) return undefined;
  const n = typeof grade === "number" ? grade : parseGrade(String(grade));
  if (n === undefined) return undefined;
  if (n <= 1) return "tk";
  if (n >= 4) return "g46";
  return undefined;
}

function parseGrade(label: string): number | undefined {
  const t = label.toLowerCase();
  if (/\btk\b|transitional/.test(t)) return 0;
  if (/kinder|\bk\b/.test(t)) return 0;
  const m = t.match(/(\d+)/);
  return m ? Number(m[1]) : undefined;
}

const CULTURES = ["zh", "hi", "es"];

/** Subject slugs we ship guaranteed fallback art for. */
const SUBJECT_ART: Record<string, string> = {
  phonics: "subj_phonics", reading: "subj_reading", math: "subj_math",
  art: "subj_art", story: "subj_story", workbooks: "subj_workbooks",
  logic: "subj_logic", feelings: "subj_feelings", manners: "subj_manners",
};

/** Topic slugs (interest themes) that have their own art. */
const TOPIC_ART = ["animals", "dinosaurs", "space", "ocean", "fantasy",
                   "vehicles", "holidays", "sports", "nature"];

/** Return a scene/word illustration for a question, or undefined if none applies. */
export function questionImage(questionText?: string, hint?: string, ctx?: ArtContext): any | undefined {
  const hay = `${questionText ?? ""}  ${hint ?? ""}`;

  // 1 · Phonics: pull the target word out of the hint and look up its object image.
  const m = hint?.match(/the word is ['"]?([a-zA-Z]+)/i);
  if (m) {
    const word = m[1].toLowerCase();
    const img = PHONICS_WORD_IMAGES[word] ?? resolve(word, ctx);
    if (img) return img;
  }

  // 2 · Hand-authored scenes (feelings / manners) win where they exist.
  for (const [re, img] of SCENE_RULES) {
    if (re.test(hay)) return img;
  }

  // 2b · Otherwise the generated scene for this exact scenario, so no two
  //      prompts in a round share a picture.
  for (const [re, name] of GENERATED_SCENES) {
    if (re.test(hay) && hasArt(name)) return { uri: "/art/" + name + ".svg" };
  }

  // 3 · Object art: a dropped-in PNG first, else the built-in glassy SVG.
  for (const [re, name] of OBJECT_RULES) {
    if (re.test(hay)) {
      const img = resolve(name, ctx);
      if (img) return img;
    }
  }

  // 4 · Fall back to the worksheet's TOPIC (dinosaurs, ocean, …), from the
  //     context or parsed out of its title.
  const topic = ctx?.topic?.toLowerCase() ?? sniff(ctx?.title, TOPIC_ART);
  if (topic) {
    const img = resolve(topic, ctx);
    if (img) return img;
  }

  // 5 · Last resort — the SUBJECT. Every question belongs to one, so from here
  //     on a card is never left bare.
  const subject = ctx?.subject?.toLowerCase() ?? sniff(ctx?.title, Object.keys(SUBJECT_ART));
  if (subject && SUBJECT_ART[subject]) {
    const img = resolve(SUBJECT_ART[subject], ctx);
    if (img) return img;
  }

  // 6 · Cultural questions carry their own track art even with no subject.
  const culture = cultureOf(hay, ctx);
  if (culture) {
    const img = resolve("culture_" + culture, ctx);
    if (img) return img;
  }

  return undefined;
}

/** Find the first known slug mentioned in a free-text title. */
function sniff(title: string | undefined, slugs: string[]): string | undefined {
  if (!title) return undefined;
  const t = title.toLowerCase();
  return slugs.find(sl => t.includes(sl));
}

/** Which culture track a question belongs to, if any. */
function cultureOf(hay: string, ctx?: ArtContext): string | undefined {
  if (ctx?.culture && CULTURES.indexOf(ctx.culture) !== -1) return ctx.culture;
  if (/[一-鿿]|pinyin|tone|tang poem/i.test(hay)) return "zh";
  if (/gita|sanskrit|diwali|namaste/i.test(hay)) return "hi";
  if (/spanish|español|españa|fiesta|día de/i.test(hay)) return "es";
  return undefined;
}

/**
 * Most specific artwork wins:
 *   dropped-in PNG  →  <name>.<culture>  →  <name>.<ageBand>  →  <name>
 */
function resolve(name: string, ctx?: ArtContext): any | undefined {
  if (OBJECT_IMAGES[name]) return OBJECT_IMAGES[name];

  const culture = ctx?.culture && CULTURES.indexOf(ctx.culture) !== -1 ? ctx.culture : undefined;
  const band = ageBand(ctx?.grade ?? (ctx?.title ? parseGrade(ctx.title) : undefined));

  for (const candidate of [
    culture ? name + "." + culture : undefined,
    band ? name + "." + band : undefined,
    name,
  ]) {
    if (!candidate) continue;
    if (OBJECT_IMAGES[candidate]) return OBJECT_IMAGES[candidate];
    if (hasArt(candidate)) return { uri: "/art/" + candidate + ".svg" };
  }
  return undefined;
}

// ── Answer-option art ────────────────────────────────────────────────────────
// Word-matched: an option whose text names something we have art for shows the
// picture BESIDE its label (never instead of it — options must stay readable).

const OPTION_WORDS: Record<string, string> = {
  // English
  apple: "apples", apples: "apples", book: "books", books: "books",
  star: "stars", stars: "stars", cookie: "cookies", cookies: "cookies",
  crayon: "crayons", crayons: "crayons", marble: "marbles", marbles: "marbles",
  stamp: "stamps", stamps: "stamps", sticker: "stickers", stickers: "stickers",
  sun: "sun", sunshine: "sun", moon: "moon", house: "house", home: "house",
  water: "water", boy: "boy", girl: "girl",
  red: "color_red", blue: "color_blue", green: "color_green",
  square: "shape_square", rectangle: "shape_rectangle", triangle: "shape_triangle",
  dinosaur: "dinosaurs", dinosaurs: "dinosaurs", space: "space", rocket: "space",
  ocean: "ocean", whale: "ocean", sea: "ocean", dragon: "fantasy",
  car: "vehicles", train: "vehicles", tree: "nature", flower: "nature",
  cake: "holidays", birthday: "holidays", lion: "animals", animal: "animals",
  animals: "animals", bear: "bear_hibernating", ball: "sports", soccer: "sports",
  // Spanish vocabulary questions ask for the meaning of these
  rojo: "color_red", azul: "color_blue", verde: "color_green",
  casa: "house", agua: "water", sol: "sun", luna: "moon",
  libro: "books", "niño": "boy", "niña": "girl",
};

/**
 * Art for a single answer option, or undefined when its wording names nothing
 * we can draw. Emotion art (happy/sad/…) keeps priority — it is purpose-drawn.
 */
export function optionImage(optionText?: string, ctx?: ArtContext): any | undefined {
  if (!optionText) return undefined;
  const raw = optionText.toLowerCase().trim();
  const key = raw.replace(/[^a-zà-ÿ\s]/gi, "").trim();

  // exact word, then any word inside a short phrase ("light and warmth")
  const direct = OPTION_WORDS[key];
  if (direct) return resolve(direct, ctx);

  for (const word of key.split(/\s+/)) {
    const name = OPTION_WORDS[word];
    if (name) return resolve(name, ctx);
  }
  // phonics object photos (cat, dog, train …) double as option art
  const phon = PHONICS_WORD_IMAGES[key];
  if (phon) return phon;
  return undefined;
}

/** Which object rules still have no artwork at all — PNG or SVG. */
export function missingQuestionImages(): string[] {
  const wanted = new Set(OBJECT_RULES.map(([, name]) => name));
  return [...wanted].filter(name => !OBJECT_IMAGES[name] && !hasArt(name)).sort();
}

/** Which rules are still running on built-in SVG rather than a real render. */
export function svgFallbackImages(): string[] {
  const wanted = new Set(OBJECT_RULES.map(([, name]) => name));
  return [...wanted].filter(name => !OBJECT_IMAGES[name] && hasArt(name)).sort();
}
