import { useQuery } from "@tanstack/react-query";
import { configApi } from "../api/config";

export function useConfig(languageId: number = 1) {
  return useQuery<Record<string, any>>({
    queryKey: ["appConfig", languageId],
    queryFn:  () => configApi.getAll(languageId) as Promise<Record<string, any>>,
    staleTime: 5 * 60 * 1000, // 5 min
    placeholderData: {
      "hero.tagline":          "One calm plan.  Nine subjects.  Your family's language.",
      "hero.subtagline":       "A 2-minute assessment builds your child's weekly plan — tap on a tablet or print on paper, you decide the screen time. Reading, math, logic, feelings, manners, art, plus three culture tracks. Written by real bilingual teachers, not an algorithm. One price covers every child.",
      "hero.cta_primary":      "Build my child's plan →",
      "hero.cta_secondary":    "See pricing",
      "hero.badge_worksheets": "100+",
      "hero.badge_languages":  "4",
      "hero.badge_price":      "1 price",
      "hero.trust": [
        "✓ 14-day free trial",
        "✓ 30-day money back",
        "✓ Cancel anytime",
        "✓ COPPA & kid-privacy-first",
        "🖨️ Tap or print — your choice",
      ],
      "hero.badges": [
        { "num": "100+", "label": "teacher-reviewed worksheets" },
        { "num": "4", "label": "home languages, done right" },
        { "num": "1 price", "label": "for up to 4 kids" },
      ],
      "hero.today_items": [
        { "icon": "📚", "label": "today's story", "sub": "Kai and the Dragon" },
        { "icon": "✏️", "label": "math practice", "sub": "2nd grade · 12 min" },
        { "icon": "🎨", "label": "art project", "sub": "Lunar lantern" },
      ],
      "dualMode.eyebrow":         "Built for busy parents",
      "dualMode.title":           "Two ways to learn.",
      "dualMode.title_highlight":"You decide screen time.",
      "dualMode.subtitle":        "Every worksheet works two ways — tap on a tablet for game-style practice, or print on paper for screen-free learning. The same lesson, your choice. Less screen guilt on the days you need it most.",
      "dualMode.divider":         "or",
      "dualMode.cards": [
        { "icon": "📱", "title": "Digital · interactive", "body": "Kids tap to fill, drag, and paint with instant feedback and audio. Auto-saves progress so they can pick up after dinner.", "features": ["Game-style chimes & confetti for ages 4-8", "Voice-over in English, 中文, हिन्दी, Español", "Phone, tablet, or laptop — no app install"] },
        { "icon": "🖨️", "title": "Print · screen-free", "body": "One click downloads a PDF — every worksheet in our library. Pencil-and-paper learning that builds the fine motor skills tablets can't.", "features": ["Letter & A4 · black-and-white friendly (toner-light)", "Quarterly printed workbook on the Family plan · Shipped", "Works on the road, in the car, at grandma's house"] },
      ],
      "dualMode.stats": [
        { "num": "0 min", "label": "screen time required" },
        { "num": "100%", "label": "printable, every worksheet" },
        { "num": "4 langs", "label": "tap or print, your call" },
      ],
      "dualMode.disclaimer":      "Why both? AAP screen time guidance + 2026 state laws (Iowa, Oklahoma, Kansas) cap classroom screens for K–5. Print-first families shouldn't have to give up modern bilingual content. We built for both.",
      "pricing.family_price":   14.99,
      "pricing.family_annual":  129,
      "pricing.shipped_price":  29.99,
      "pricing.shipped_annual": 299,
      "pricing.family_save":    51,
      "pricing.shipped_save":   61,
      "community.officehours_day":   "Wednesday",
      "community.officehours_time":  "7:00 pm PT",
      "community.officehours_host":  "Ms. Chen · credentialed bilingual teacher",
      "community.officehours_topic": "How to introduce Tang Shi to a 1st grader without overwhelming them",
      "community.officehours_next":  "Wed 29",
      "community.discord_url":       "#",
      "community.discord_members":   "1,240",
      "community.wechat_members":    "860",
      "community.whatsapp_hindi_members":   "520",
      "community.whatsapp_espanol_members": "740",
      "community.groups": [
        { "flag": "🇺🇸", "label": "English-speaking parents", "platform": "Discord", "members": "1,240" },
        { "flag": "🏮", "label": "华人家长群 · Chinese-speaking parents", "platform": "WeChat", "members": "860" },
        { "flag": "🪔", "label": "हिन्दी parents & Gita circle", "platform": "WhatsApp", "members": "520" },
        { "flag": "🌻", "label": "Familias en español", "platform": "WhatsApp", "members": "740" },
      ],
      "referral.code_example":  "LSH-FAM-2026",
      "referral.description":   "Your referral gets their first month of Family free. When they subscribe, your next month is on us.",
      "social.tiktok_handle":       "@littlescholarshub",
      "social.instagram_handle":    "@littlescholarshub",
      "social.xiaohongshu_handle":  "小学霸中心 · LittleScholarsHub",
      "social.cards": [
        { "desc": "60-second phonics and math hooks. Moms and teachers, English + Spanish." },
        { "desc": "Weekly worksheet drops, flat-lays, reels. The aesthetic homeschool crowd." },
        { "desc": "双语拼音、阅读、数学练习册，给美国华人家庭的放学后学习方式。" },
      ],
      "school.plans": [
        { "label": "Classroom", "price": "$4/student/month", "desc": "For a single classroom (up to 30 students).", "features": ["All 9 subjects + 3 culture tracks", "Teacher dashboard with per-student progress", "Printable class-set worksheets", "PD: 1 hr onboarding for the teacher"] },
        { "label": "Afterschool program", "price": "$3/student/month", "desc": "For community orgs & afterschool centers.", "features": ["Everything in Classroom", "Session-planning kits (60-min blocks)", "Mandarin, Spanish, or Hindi instructor guides", "Parent communication templates"] },
        { "label": "District", "price": "Custom", "desc": "100+ seats with admin console.", "features": ["Volume pricing (from $2/student/mo)", "District admin dashboard & reporting", "SSO (Clever / ClassLink / Google)", "COPPA & FERPA-aligned data agreements", "Dedicated partner success manager"] },
      ],
      "footer.links": ["Subjects", "Worksheets", "Pricing", "About", "For Teachers", "Contact", "TikTok", "Instagram", "Xiaohongshu", "YouTube"],
      "footer.company_links": ["About", "For Teachers", "Contact"],
      "footer.social_links": ["TikTok", "Instagram", "Xiaohongshu", "YouTube"],
      "footer.legal": ["Privacy", "Terms"],
      "footer.copy": "© 2026 Little Scholars Hub — all curriculum, code & content protected.",
      "footer.tagline": "Afterschool and homeschool learning for TK–6. Printable, bilingual, and built for busy families.",
      "worksheets.grades": ["TK","Kindergarten","1st","2nd","3rd","4th","5th","6th"],
      "worksheets.tags": ["Phonics","Reading","Writing","Math","Logic","Science","Art","Feelings","Manners","Story","Workbooks","Pinyin","汉字","唐诗","Gita","Letras","Fiestas","Maestros"],
      "whyUs.items": [
        { "n": "01", "title": "Heritage language, done right", "body": "Every core worksheet is also available in Mandarin, Hindi, and Spanish — translated by real bilingual teachers, not machines." },
        { "n": "02", "title": "Printable + interactive", "body": "Get the PDF to print for screen-free practice, and track progress with bite-size digital practice on phone or tablet." },
        { "n": "03", "title": "Story-first, not drill-first", "body": "Every week ties around one story. Kids learn vocabulary, math, and art connected to that world — so concepts stick." },
      ],
      "testimonials.items": [
        { "stars": 5, "badge": "✓ Verified family · 7-mo subscriber", "quote": "The Pinyin → 100字 → 唐诗 sequence is exactly what I've been trying to DIY for a year. My 2nd grader recited 静夜思 to her grandma on WeChat last weekend — 外婆 cried.", "name": "Lily J. · 贾莉", "location": "Bay Area · daughters, grades K & 2" },
        { "stars": 5, "badge": "✓ Verified family · 4-mo subscriber", "quote": "I finally have a homeschool plan that includes the Gita stories I grew up with — my son asks for the \"Words for Today\" at breakfast. Not one of the big platforms had anything like this.", "name": "Priya R. · प्रिया", "location": "New Jersey · homeschool, 1st & 4th" },
        { "stars": 5, "badge": "✓ Familia verificada · 5 meses", "quote": "Los cuentos de Día de los Muertos, el alfabeto con la ñ, los maestros como Frida — mi hija se siente orgullosa de las dos culturas. No es una simple traducción, está hecho con cariño.", "name": "María D.", "location": "Los Ángeles · hija de 3er grado" },
      ],
      "progress.cards": [
        { "subject": "Reading · 1st grade", "w1": "still guessing \"the\"", "w12": "reads 32 sight words ✨", "name": "Aanya's phonics climb", "desc": "Pre-reader → reading short chapter pages aloud", "quote": "We stopped doing worksheet drills and let the daily story pull her forward. 12 weeks." },
        { "subject": "Math · 3rd grade", "w1": "7 × ? = 🤷 times tables: foggy", "w12": "1–10 × fluent\nsolving 2-step word ✅", "name": "Noah's math fluency", "desc": "\"Foggy\" → 2-step word problems, unprompted", "quote": "Singapore bar models + 10 min/day. He asked for the workbook on our road trip." },
        { "subject": "汉字 · 2nd grade", "w1": "一二三 — 3 characters", "w12": "48 characters\nrecited 静夜思 to 外婆", "name": "Mei's 汉字 journey", "desc": "3 characters → 48 + first Tang poem", "quote": "外婆 on WeChat cried. That's a ROI I didn't know we were buying." },
      ],
      "comparison.items": [
        { "complaint": "\"Everyone uses AI — no real teacher ever sees my kid's work.\"", "answer": "Every worksheet in your weekly plan is written and reviewed by a credentialed bilingual teacher." },
        { "complaint": "\"The scoring system punishes mistakes and stresses my kid out.\"", "answer": "No red marks. Kids check their own work with answer keys; parents see effort & streak, not pass/fail." },
        { "complaint": "\"It feels like busywork with no rigor.\"", "answer": "Our assessment weights your child's actual level. The plan is a sequence with clear end goals." },
        { "complaint": "\"There's nothing for my bilingual kid.\"", "answer": "Three fully sequenced culture-infused programs — Chinese, Indian, Hispanic — translated by real educators." },
        { "complaint": "\"Per-child pricing adds up fast.\"", "answer": "One price covers up to four kids. Annual plans save an additional 17–28%." },
        { "complaint": "\"My kid's progress got wiped when the app updated.\"", "answer": "Weekly progress exports to a printable PDF. Cloud-backed account keeps their streak across devices." },
      ],
      "feature.kid_mode_enabled":     true,
      "feature.office_hours_enabled": true,
      "feature.referral_enabled":     true,
    },
  });
}
