-- 33_solar_system_content.sql
-- First batch of Solar System subject content, curated from Archive.org's
-- solarsystemcollection (NASA/JPL public-domain photos and mission
-- graphics -- see https://archive.org/details/solarsystemcollection).
-- Reuses the existing Worksheets table/content-library pipeline rather than
-- a new table: content_type='space_image', pdf_url is the full-resolution
-- image (opened the same way a worksheet PDF is), thumbnail_url uses
-- archive.org's universal thumbnail service. Titles/captions below are
-- original kid-level rewrites, not copies of the NASA archival description.
-- Requires 32_stories_media_and_solar_system.sql (adds the Solar System
-- subject, subject_id=17) to have run first.

INSERT INTO dbo.Worksheets (subject_id, grade_id, content_type, title, description, estimated_min, page_count, pdf_url, thumbnail_url, teacher_name)
VALUES
(17, 0, 'space_image', N'Six Wheels on Mars', N'This little robot car is called a rover! It has six wheels and drives around Mars taking pictures for scientists on Earth.', 5, 1, 'https://archive.org/download/SPD-SLRSY-943/Spirit_Rollout.jpg', 'https://archive.org/services/img/SPD-SLRSY-943', N'NASA / Archive.org (Solar System Collection)'),
(17, 0, 'space_image', N'Our Moon from Space', N'A spaceship named Galileo took this picture of our Moon as it flew by on its way to explore other planets.', 5, 1, 'https://archive.org/download/SPD-SLRSY-2094/PIA00405.jpg', 'https://archive.org/services/img/SPD-SLRSY-2094', N'NASA / Archive.org (Solar System Collection)'),
(17, 1, 'space_image', N'How Planets Travel Around the Sun', N'Planets don''t just sit still — they travel around the Sun in big circles called orbits, like cars going around a racetrack!', 5, 1, 'https://archive.org/download/SPD-SLRSY-174/vis_orb.jpg', 'https://archive.org/services/img/SPD-SLRSY-174', N'NASA / Archive.org (Solar System Collection)'),
(17, 1, 'space_image', N'When the Moon Blocks the Sun', N'See that dark shadow on Earth? That''s the Moon''s shadow! It happens during a solar eclipse, when the Moon moves between the Sun and the Earth.', 5, 1, 'https://archive.org/download/SPD-SLRSY-189/earth_eclipse.jpg', 'https://archive.org/services/img/SPD-SLRSY-189', N'NASA / Archive.org (Solar System Collection)'),
(17, 2, 'space_image', N'The Asteroid Belt', N'Between Mars and Jupiter, there''s a huge ring of rocky space leftovers called asteroids — pieces left over from when our solar system was forming!', 5, 1, 'https://archive.org/download/SPD-SLRSY-850/Asteroid_Belt.jpg', 'https://archive.org/services/img/SPD-SLRSY-850', N'NASA / Archive.org (Solar System Collection)'),
(17, 2, 'space_image', N'Rover Tracks on Mars', N'A rover named Opportunity left these tire tracks in the red Martian dirt as it explored the surface of Mars, taking photos and testing rocks.', 5, 1, 'https://archive.org/download/SPD-SLRSY-1223/Opp_Rollout.jpg', 'https://archive.org/services/img/SPD-SLRSY-1223', N'NASA / Archive.org (Solar System Collection)'),
(17, 3, 'space_image', N'What Is a Comet?', N'A comet is a giant snowball made of ice, dust, and rock. When it gets close to the Sun, it grows a bright, glowing tail that can stretch for millions of miles!', 5, 1, 'https://archive.org/download/SPD-SLRSY-20/kids-Comets006.jpg', 'https://archive.org/services/img/SPD-SLRSY-20', N'NASA / Archive.org (Solar System Collection)'),
(17, 3, 'space_image', N'An Asteroid With Its Own Moon', N'Meet Ida — a big asteroid — and Dactyl, its very own tiny moon! This was one of the first times scientists discovered an asteroid that had a moon circling it.', 5, 1, 'https://archive.org/download/SPD-SLRSY-888/Enhanced_Ida-browse.jpg', 'https://archive.org/services/img/SPD-SLRSY-888', N'NASA / Archive.org (Solar System Collection)'),
(17, 4, 'space_image', N'Rhea, One of Saturn''s Moons', N'Rhea is Saturn''s second-largest moon, covered in ice and craters. This picture was taken by the Voyager 1 spacecraft as it zoomed past in 1980.', 5, 1, 'https://archive.org/download/SPD-SLRSY-841/Rhea.jpg', 'https://archive.org/services/img/SPD-SLRSY-841', N'NASA / Archive.org (Solar System Collection)'),
(17, 4, 'space_image', N'Where Apollo 11 Landed on the Moon', N'In 1969, astronauts picked this smooth, flat area on the Moon to land safely — it''s where Neil Armstrong took the very first human steps on the Moon!', 5, 1, 'https://archive.org/download/SPD-SLRSY-805/Apollo11_Site-browse.jpg', 'https://archive.org/services/img/SPD-SLRSY-805', N'NASA / Archive.org (Solar System Collection)'),
(17, 5, 'space_image', N'A Full Picture of Jupiter', N'This close-up photo of Jupiter was stitched together from several pictures taken by the New Horizons spacecraft. You can see Jupiter''s swirling clouds and famous stripes.', 5, 1, 'https://archive.org/download/SPD-SLRSY-5163/PIA09243_modest.jpg', 'https://archive.org/services/img/SPD-SLRSY-5163', N'NASA / Archive.org (Solar System Collection)'),
(17, 5, 'space_image', N'Pluto and Its Moon, Charon', N'Pluto is a dwarf planet way out at the edge of our solar system, and Charon is its largest moon. This is one of the clearest pictures ever taken of them together, from the Hubble Space Telescope.', 5, 1, 'https://archive.org/download/SPD-SLRSY-2100/PIA00827.jpg', 'https://archive.org/services/img/SPD-SLRSY-2100', N'NASA / Archive.org (Solar System Collection)'),
(17, 6, 'space_image', N'A Spacecraft''s Journey to Saturn', N'This diagram shows the path the Cassini-Huygens spacecraft took to reach Saturn and settle into orbit around it, after traveling through space for almost 7 years.', 5, 1, 'https://archive.org/download/SPD-SLRSY-2623/Cassini_SOI.jpg', 'https://archive.org/services/img/SPD-SLRSY-2623', N'NASA / Archive.org (Solar System Collection)'),
(17, 6, 'space_image', N'A Volcano Erupting on Io', N'Io, one of Jupiter''s moons, has the most active volcanoes in our entire solar system! This picture from the Voyager 1 spacecraft captured one erupting.', 5, 1, 'https://archive.org/download/SPD-SLRSY-129/PIA01971.jpg', 'https://archive.org/services/img/SPD-SLRSY-129', N'NASA / Archive.org (Solar System Collection)'),
(17, 7, 'space_image', N'New Horizons'' Journey to Pluto', N'This artist''s drawing shows the New Horizons spacecraft as it flew past Pluto and its moon Charon in 2015, after a 9-year journey across the solar system.', 5, 1, 'https://archive.org/download/SPD-SLRSY-546/NewHorizons_Pluto.jpg', 'https://archive.org/services/img/SPD-SLRSY-546', N'NASA / Archive.org (Solar System Collection)'),
(17, 7, 'space_image', N'Galileo''s Arrival at Jupiter', N'This artist''s rendering shows the Galileo spacecraft arriving at Jupiter in 1995. It dropped a smaller probe into Jupiter''s thick atmosphere to gather data.', 5, 1, 'https://archive.org/download/SPD-SLRSY-2064/Jupiter_Arrival.jpg', 'https://archive.org/services/img/SPD-SLRSY-2064', N'NASA / Archive.org (Solar System Collection)'),
(17, 7, 'space_image', N'Exploring Titan, Saturn''s Foggy Moon', N'This artist''s concept imagines Titan''s surface, with Saturn glowing faintly through Titan''s thick, hazy atmosphere. Titan is the only moon in our solar system with a real atmosphere!', 5, 1, 'https://archive.org/download/SPD-SLRSY-3963/CraigAttebery_huygens.jpg', 'https://archive.org/services/img/SPD-SLRSY-3963', N'NASA / Archive.org (Solar System Collection)'),
(17, 7, 'space_image', N'The Five Largest Moons of Uranus', N'This ''family portrait'' shows Uranus'' five largest moons side by side, put together from pictures the Voyager 2 spacecraft sent back in 1986.', 5, 1, 'https://archive.org/download/SPD-SLRSY-2123/PIA01975-browse.jpg', 'https://archive.org/services/img/SPD-SLRSY-2123', N'NASA / Archive.org (Solar System Collection)');
GO
