-- 41_weekly_packets.sql
-- "Weekly Worksheet Packet by Grade" — a dynamically-generated, multi-page
-- PDF packet (drills + word problems + patterns + word puzzles) scoped to a
-- grade and a specific calendar week, in the spirit of commercial
-- weekly-packet products (e.g. MathWorksheets.com) but with entirely
-- original, hand-authored problems/layout generated by
-- services/worksheet_pdf_generator.py — no third-party content reproduced.
--
-- First rollout: 1st grade only, 3 upcoming weeks, to validate the format
-- before expanding to more grades/weeks in a later batch.

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.Worksheets') AND name = 'week_of')
BEGIN
    ALTER TABLE dbo.Worksheets ADD week_of DATE NULL;
END
GO

IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = 'CK_WS_ContentType')
BEGIN
    ALTER TABLE dbo.Worksheets DROP CONSTRAINT CK_WS_ContentType;
END
GO

ALTER TABLE dbo.Worksheets ADD CONSTRAINT CK_WS_ContentType
    CHECK (content_type IN ('workbook', 'mini_book', 'coloring', 'worksheet', 'space_image', 'iacl_book', 'weekly_packet'));
GO

INSERT INTO dbo.Worksheets
    (subject_id, grade_id, title, description, estimated_min, pdf_generator_key, teacher_name, content_type, week_of, is_free)
VALUES
(6, 2, N'1st Grade Weekly Packet — Week of Aug 10, 2026', N'A full week of original math drills, word problems, patterns, and word play for 1st grade.', 40, 'weekly_packet_g1_w1', N'Little Scholars Hub Team', 'weekly_packet', '2026-08-10', 1),
(6, 2, N'1st Grade Weekly Packet — Week of Aug 17, 2026', N'A full week of original math drills, word problems, patterns, and word play for 1st grade.', 40, 'weekly_packet_g1_w2', N'Little Scholars Hub Team', 'weekly_packet', '2026-08-17', 1),
(6, 2, N'1st Grade Weekly Packet — Week of Aug 24, 2026', N'A full week of original math drills, word problems, patterns, and word play for 1st grade.', 40, 'weekly_packet_g1_w3', N'Little Scholars Hub Team', 'weekly_packet', '2026-08-24', 1);
GO
